### ISSUE TITLE
Stuttering when driving.

### ISSUE THREAD

**Issue by sxck1335** [LukeRoss00/gta5-real-mod#153]
Hey,
At first I want to say thanks for this insane mod. Its very nice and makes much fun, but It starts stuttering or vibrating when I drive in a car so its kinda wierd and hard to explain. When I'm not driving and just walking etc it's veeery smooth. I got a oculus rift. Not the S version. Maybe someone can help or provide a thread where people got the same problem.
Keep the good work🙏🏽
Greeting, sxck

**Comment by sxck1335** [comment]
Nvm I fixed it but why the game just sees 2gb of my 4gb vram from my graphics card?

**Comment by Trickypreece** [comment]
How did you fix it? I get a stutter whilst in car.

**Comment by sxck1335** [comment]
> How did you fix it? I get a stutter whilst in car.

Just lower ur settings in with the bat file. But still GTA just shows half of my video memory so I have to play on low settings and it looks so crappy... When I play GTA without this mod it recognizes my 4gb video memory. With the mod it just sees 2gb.. kinda wierd.

**Comment by KptnKMan** [comment]
I always assumed this is because VR renders your game twice, which effectively screws with the metrics.

Im not an expert in this, maybe the mod dev can comment and clarify.

**Comment by LukeRoss00** [comment]
My mod doesn't behave like that. In fact, with AER the rendering rate is NOT doubled, which is what makes it possible to run GTA V in VR at acceptable frame rates.

Nobody else has reported this graphics memory issue, and I cannot reproduce it here. About the stuttering when driving, I'm not sure what you mean. Does it happen in monoscopic mode too?

**Comment by sxck1335** [comment]
Thanks for the answer, I fixed the stuttering, it where just too hight setting that I choose. But normally I have more video ram. Because when I use the mod I just got 2gb video memory instead of 4gb that's why I can only play on low settings and Medium makes it stutter, I can upload a video tomorrow to show you exactly what I mean.

**Comment by LukeRoss00** [comment]
This is the first time I hear of the problem you're seeing with VRAM. On my system, GTA V always reports exactly the same amount of video memory in each case: a. mod disabled and Oculus runtime disabled, b. mod disabled and Oculus runtime enabled, c. mod enabled and running in VR.

**Comment by Goodclaimer** [comment]
Hello folks, any news about this? Having same kind of issue here. Mainly stuttering occurs when driving + turning left or right, even on foot while im moving the camera around the caracter in 3rd person mode. When turning my head, its not creating the issue. I have tried a lot of things found in may topics, ex: set post fx : to normal, different setting L/M/H.

My config should not be a problem,
Rog strix z390-e + Intel 9700k processor.
Nvidia Rtx2070, 8gb
Valve Index headset

I have notice some difference when disable Async for reproduction ratio in FPSVr app. But it is inverting the problem. Stuttering occur at moving head but its less noticable on camera play.. don't know if it helps.

Thks for your support!

**Comment by LukeRoss00** [comment]
Not sure if it's relevant to your problems, but please note that neither ASW (for Oculus) nor Motion Smoothing (for SteamVR) are compatible with alternate eye rendering, so they should be _disabled_ when using my mod.

**Comment by Goodclaimer** [comment]
Thanks, it helps a lot, game is running a way better in M setting, still not perfect in H setting, but it could be related to my setup. Great job by the way, if you find other tricks please let me know, to bring it almost perfect as a native AAA Vr game, that wpuld be awsome
